/*
 Lofty, v0.1 http://lofty.fangdeng.org/ MIT
*/
(function(b){if(!b.lofty){var f={},e=function(a,c,d){if(!f[a]){d||(d=c,c=[]);a=f[a]={id:a,deps:c,factory:d};if("function"===typeof a.factory){c=[];d=a.deps;for(var b=0,h=d.length;b<h;b++)c.push(g(d[b]));a.exports=a.factory.apply(e,c)}else a.exports=a.factory;delete a.factory}},g=function(a){return(a=f[a])?a.exports:null};e.version="0.1";e.cache={kernel:f};e("global",b);e("require",function(){return g});b.lofty=e}})(this);
lofty("lang",function(){var f={}.toString,e=Array.prototype,g={isFunction:function(a){return"[object Function]"===f.call(a)},isArray:Array.isArray||function(a){return"[object Array]"===f.call(a)},isString:function(a){return"string"===typeof a},forEach:e.forEach?function(a,c,b){a.forEach(c,b)}:function(a,c,b){for(var d=0,e=a.length;d<e;d++)c.call(b,a[d],d,a)},map:e.map?function(a,c,b){return a.map(c,b)}:function(a,c,b){var d=[];g.forEach(a,function(a,e,f){d.push(c.call(b,a,e,f))});return d},indexOf:e.indexOf?
function(a,c){return a.indexOf(c)}:function(a,c){for(var b=0,d=a.length;b<d;b++)if(a[b]===c)return b;return-1}};return g});
lofty("event",function(){var b=this.cache.events={},f=[].slice;return{on:function(a,c){(b[a]||(b[a]=[])).push(c)},emit:function(a){var c=f.call(arguments,1),d=b[a],e,g=0;if(d)for(;e=d[g++];)e.apply(null,c)}}});
lofty("config",["lang"],function(l){var a=this.cache,e=a.config={},d=a.configRules={},a={addRule:function(b,c){d[b]={rule:c,keys:[]};return this},addRuleKey:function(b,c){d[c]&&d[c].keys.push(b);return this}};a.addRule("object",function(b,c,h){if(b){for(var a in h)b[a]=h[a];return!0}return!1}).addRule("array",function(b,c,a){b?b.push(a):this[c]=[a];return!0});this.config=function(b){for(var c in b){var a=b[c],m=e[c],j=c,n=a,f=!1,g=void 0,k=void 0;for(k in d)if(f)break;else g=d[k],f=-1<l.indexOf(g.keys,
j)&&g.rule.call(e,m,j,n);f||(e[c]=a)}};return a});
lofty("alias",["config","event"],function(d,e){var f=this.cache.config;d.addRuleKey("alias","object");return function(a){var b=f.alias,c;if(b&&(c=b[a.id]))a.id=c;e.emit("alias",a)}});
lofty("module",["global","lang","event","alias"],function(g,h,f,m){var n=[],k=0,j=this.cache.modules={},d={get:function(a){a={id:a};m(a);return j[a.id]},has:function(a){return d.get(a)||l[a]?!0:!1},hasDefine:function(a){return j[a]?!0:!1},isAnon:function(a){return""===a.id},save:function(a){j[a._id||a.id]=a},autocompile:function(a){d.isAnon(a)&&d.compile(a)},compile:function(a){try{if(h.isFunction(a.factory)){var b=[],e=a.deps;h.isArray(e)&&h.forEach(e,function(c){var e;c=(e=l[c])?e(a):d.require(c,
a);b.push(c)});var c=a.factory.apply(null,b);void 0!==c?a.exports=c:a.entity&&(a.exports=a.entity.exports);a.entity&&delete a.entity}else void 0!==a.factory&&(a.exports=a.factory);f.emit("compiled",a)}catch(g){f.emit("compileFail",g,a)}},require:function(a){var b=d.get(a);b?(b.visits||(b.visits++,d.compile(b)),f.emit("required",b),a=b.exports):(f.emit("requireFail",{id:a}),a=null);return a}},p=function(a,b,d){this.id=a;this.deps=b||[];this.factory=d;this.exports={};this.visits=0;""===a&&(a="__!_lofty_anonymous_"+
k,k++,this._id=a)},l={require:function(){function a(a){return d.require(a)}f.emit("makeRequire",a);return a},exports:function(a){return a.exports},module:function(a){a.entity={id:a.id,exports:a.exports};return a.entity}},q=g.define;this.noConflict=function(){g.define=q};this.define=function(a,b,e){var c;c=arguments.length;1===c?(e=a,a=""):2===c&&(e=b,b=n,h.isString(a)||(b=a,a=""));if(d.hasDefine(a))return f.emit("existed",{id:a}),null;c=new p(a,b,e);f.emit("define",c);d.save(c);d.autocompile(c)};
g.define=this.define;return d});
lofty("loader",["global"],function(h){var j=this.cache.config,f=h.document,p=/\.css(?:\?|$)/,l=/loaded|complete|undefined/,q=536>1*h.navigator.userAgent.replace(/.*AppleWebKit\/(\d+)\..*/,"$1"),k=f&&(f.head||f.getElementsByTagName("head")[0]||f.documentElement),m=f.getElementsByTagName("base")[0],n=function(a,b){a.onerror=function(){a.onload=a.onreadystatechange=a.onerror=null;a=void 0;b&&b()}};return function(a,b){var c;if(p.test(a)){var d=c=f.createElement("link");if(q||!("onload"in d)){var g=f.createElement("img");
g.onerror=function(){b();g.onerror=null;g=void 0};g.src=a}else d.onload=d.onreadystatechange=function(){l.test(d.readyState)&&(d.onload=d.onreadystatechange=d.onerror=null,d=void 0,b&&b())},n(d,b);c.rel="stylesheet";c.href=a}else{var e=c=f.createElement("script");e.onload=e.onreadystatechange=function(a){a=a||h.event;if("load"===a.type||l.test(e.readyState))e.onload=e.onreadystatechange=e.onerror=null,j.debug||k.removeChild(e),e=void 0,b&&b()};n(e,b);c.async=!0;c.src=a}j.charset&&(c.charset=j.charset);
m?k.insertBefore(c,m):k.appendChild(c)}});
lofty("id2url",["global","event","config","alias"],function(a,g,e,h){var d=this.cache.config,j=/\?|\.(?:css|js)$|\/$/,k=/^https?:\/\//,l=(new Date).getTime();a=a.document.getElementsByTagName("script");a=a[a.length-1];a=(a.hasAttribute?a.src:a.getAttribute("src",4)).match(/([\w]+)\:\/\/([\w|\.|\:]+)\//i);d.baseUrl=a[0];e.addRuleKey("resolve","array").addRuleKey("stamp","object");return function(b){h(b);var a=d.resolve,c;if(a)for(var f=0,e=a.length;f<e&&!(c=a[f](b.id),c!==b.id);f++);b.url=c?c:b.id;
k.test(b.url)||(b.url=d.baseUrl+b.url);!j.test(b.url)&&(b.url+=".js");a=d.hasStamp?l:null;(c=d.stamp)&&c[b.id]&&(a=c[b.id]);a&&(b.url+="?lofty.stamp="+a);g.emit("id2url",b)}});
lofty("request",["global","event","loader","id2url"],function(j,k,l,m){var e=this.cache,f=e.config,g=e.assets={};f.loadTimeout=1E4;var h=function(b,c){if(!b.timeout){j.clearTimeout(b.timer);var d,a;c?(b.status=2,a=b.callQueue):(b.status=-1,a=b.errorQueue);for(;d=a.shift();)d()}};return function(b,c,d){var a;b={id:b};m(b);a=g[b.url]||(g[b.url]=b);2===a.status?c&&c():(a.callQueue?a.callQueue.push(c):a.callQueue=[c],a.errorQueue?a.errorQueue.push(d):a.errorQueue=[d],1!==a.status&&(a.status=1,a.timer=
setTimeout(function(){a.timeout=!0;h(a,!1);k.emit("requestTimeout",a)},f.loadTimeout),l(a.url,function(){h(a,!0)})))}});
lofty("deferred",function(){var h=function(){},k=function(a){var e=this,d=[],f=0,c=0;a=a||1;var g=function(){e.then=!c?function(a){a&&a()}:function(a,b){b&&b()};g=h;j(!c?0:1);j=h;d=[]},j=function(a){for(var b,c=0;b=d[c++];)(b=b[a])&&b()};this.then=function(a,b){d.push([a,b])};this.resolve=function(){f++;f+c===a&&g()};this.reject=function(){c++;f+c===a&&g()}};return function(){for(var a=new k(arguments.length),e,d=0;e=arguments[d++];)e(a);return a}});
lofty("use",["lang","event","module","request","deferred"],function(d,j,f,k,g){var e={realize:function(a,b){d.isArray(a)||(a=[a]);e.load(a,function(){var c=d.map(a,function(a){return f.require(a)});b&&b.apply(null,c)})},load:function(a,b){var c=[];d.forEach(a,function(a){f.has(a)||c.push(a)});c.length?e.fetch(c,b):b()},fetch:function(a,b){e.get(a,function(){g.apply(null,d.map(a,function(a){return function(b){var h=f.get(a);h?e.load(h.deps,function(){b.resolve()}):b.resolve()}})).then(b)})},get:function(a,
b,c){g.apply(null,d.map(a,function(a){return function(b){f.has(a)?b.resolve():k(a,function(){b.resolve()},function(){b.reject()})}})).then(b,c)}};j.on("makeRequire",function(a){a.use=function(a,c,d){e.realize(a,c,d)}});return e});
lofty("debug",["global","config","console","request","require"],function(b,d,a,e,g){var h=this,j=this.log=function(){};d.addRule("debug",function(d,k,f){h.log=f?b.console?function(a,c){b.console[c||"log"](a)}:function(b,c){a?a(b,c):e&&e("lofty/kernel/console",function(){a||(a=g("console"));a(b,c)})}:j;this[k]=f;return!0}).addRuleKey("debug","debug")});
lofty("alicn",["global","event"],function(b,c){var e=/\.css(?:\?|$)/;this.config({hasStamp:!0,resolve:function(a){var b=a.split("/"),c=b[0],d=e.test(a)?"css/":"js/";switch(c){case "lofty":case "makeup":a="/fdevlib/"+d+a;break;case "sys":a="/sys/"+d+b.slice(1).join("/")}return a},debug:function(){var a=!1;0<b.location.href.indexOf("lofty.debug=true")&&(a=!0);return a}()});this.appframe=function(a){b[a]={log:this.log,define:this.define,on:c.on}}});
