/*
 Lofty, v0.1 http://lofty.fangdeng.org/ MIT
*/
(function(b){if(!b.lofty){var f={},c=function(a,d,e){if(!f[a]){e||(e=d,d=[]);a=f[a]={id:a,deps:d,factory:e};if("function"===typeof a.factory){d=[];e=a.deps;for(var b=0,g=e.length;b<g;b++)d.push(h(e[b]));a.exports=a.factory.apply(c,d)}else a.exports=a.factory;delete a.factory}},h=function(a){return(a=f[a])?a.exports:null};c.version="0.1";c.log=b.console?function(a,b){console[b||"log"](a)}:function(){};c.cache={kernel:f};c("global",b);c("cache",c.cache);b.lofty=c}})(this);
lofty("lang",function(){var g={}.hasOwnProperty,e=Array.prototype,f={slice:[].slice,hasOwn:function(a,b){return g.call(a,b)},isFunction:function(a){return"[object Function]"===this.toString.call(a)},isArray:Array.isArray||function(a){return"[object Array]"===this.toString.call(a)},isString:function(a){return"string"===typeof a},forEach:e.forEach?function(a,b,c){a.forEach(b,c)}:function(a,b,c){for(var d=0,e=a.length;d<e;d++)b.call(c,a[d],d,a)},map:e.map?function(a,b,c){return a.map(b,c)}:function(a,
b,c){var d=[];f.forEach(a,function(a,e,f){d.push(b.call(c,a,e,f))});return d},indexOf:e.indexOf?function(a,b){return a.indexOf(b)}:function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1}};return f});
lofty("event",["lang","cache"],function(d,f){var b=f.events={};return{on:function(a,c){(b[a]||(b[a]=[])).push(c)},emit:function(a){var c=d.slice.call(arguments,1),e=b[a];e&&d.forEach(e,function(a){a.apply(null,c)})}}});
lofty("config",["global","cache","lang"],function(k,h,j){var g=h.config={},f=h.configRules={},e={realize:function(b){for(var a in b)if(j.hasOwn(b,a)){var c=b[a];e.applyRules(g[a],a,c)||(g[a]=c)}},addRule:function(b,a){f[b]={rule:a,keys:[]};return this},addRuleKey:function(b,a){f[a]&&f[a].keys.push(b);return this},applyRules:function(b,a,c){var d=!1,e;for(e in f)if(d)break;else d=f[e],d=-1<j.indexOf(d.keys,a)&&d.rule(b,a,c);return d}};e.addRule("object",function(b,a,c){if(b){for(var d in c)b[d]=c[d];
return!0}return!1}).addRule("array",function(b,a,c){b?b.push(c):g[a]=[c];return!0});this.config=e.realize;return e});
lofty("alias",["cache","config","event"],function(d,e,f){var g=d.config;e.addRuleKey("alias","object");f.on("alias",function(a){var b=g.alias,c;if(b&&(c=b[a.id]))a.id=c})});
lofty("module",["global","cache","lang","event"],function(g,m,h,d){var n=[],k=0,j=m.modules={},e={get:function(a){a={id:a};d.emit("alias",a);return j[a.id]},has:function(a){return e.get(a)||l[a]?!0:!1},hasDefine:function(a){return j[a]?!0:!1},isAnon:function(a){return""===a.id},save:function(a){j[a._id||a.id]=a},autocompile:function(a){e.isAnon(a)&&e.compile(a)},compile:function(a){try{if(h.isFunction(a.factory)){var b=[],f=a.deps;h.isArray(f)&&h.forEach(f,function(c){var d;c=(d=l[c])?d(a):e.require(c,
a);b.push(c)});var c=a.factory.apply(null,b);void 0!==c?a.exports=c:a.entity&&(a.exports=a.entity.exports);a.entity&&delete a.entity}else void 0!==a.factory&&(a.exports=a.factory);d.emit("compiled",a)}catch(g){d.emit("compileFail",g,a)}},require:function(a){var b=e.get(a);b?(b.visits||(b.visits++,e.compile(b)),d.emit("required",b),a=b.exports):(d.emit("requireFail",{id:a}),a=null);return a}},p=function(a,b,d){this.id=a;this.deps=b||[];this.factory=d;this.exports={};this.visits=0;""===a&&(a="__!_lofty_anonymous_"+
k,k++,this._id=a)},l={require:function(){function a(a){return e.require(a)}d.emit("makeRequire",a);return a},exports:function(a){return a.exports},module:function(a){a.entity={id:a.id,exports:a.exports};return a.entity}},q=g.define;this.noConflict=function(){g.define=q};this.define=function(a,b,f){var c;c=arguments.length;1===c?(f=a,a=""):2===c&&(f=b,b=n,h.isString(a)||(b=a,a=""));if(e.hasDefine(a))return d.emit("existed",{id:a}),null;c=new p(a,b,f);d.emit("define",c);e.save(c);e.autocompile(c)};
g.define=this.define;return e});
lofty("loader",["cache","global"],function(p,h){var j=p.config,f=h.document,q=/\.css(?:\?|$)/,l=/loaded|complete|undefined/,r=536>1*h.navigator.userAgent.replace(/.*AppleWebKit\/(\d+)\..*/,"$1"),k=f&&(f.head||f.getElementsByTagName("head")[0]||f.documentElement),m=f.getElementsByTagName("base")[0],n=function(a,b){a.onerror=function(){a.onload=a.onreadystatechange=a.onerror=null;a=void 0;b&&b()}};return function(a,b){var c;if(q.test(a)){var d=c=f.createElement("link");if(r||!("onload"in d)){var g=
f.createElement("img");g.onerror=function(){b();g.onerror=null;g=void 0};g.src=a}else d.onload=d.onreadystatechange=function(){l.test(d.readyState)&&(d.onload=d.onreadystatechange=d.onerror=null,d=void 0,b&&b())},n(d,b);c.rel="stylesheet";c.href=a}else{var e=c=f.createElement("script");e.onload=e.onreadystatechange=function(a){a=a||h.event;if("load"===a.type||l.test(e.readyState))e.onload=e.onreadystatechange=e.onerror=null,j.debug||k.removeChild(e),e=void 0,b&&b()};n(e,b);c.async=!0;c.src=a}j.charset&&
(c.charset=j.charset);m?k.insertBefore(c,m):k.appendChild(c)}});
lofty("path",["global","cache","config","event"],function(a,g,h,f){var d=g.config;a=a.document;var j=/\?|\.(?:css|js)$|\/$/,k=/^https?:\/\//,l=(new Date).getTime();d.protocol="http";a=a.getElementsByTagName("script");a=a[a.length-1];a=(a.hasAttribute?a.src:a.getAttribute("src",4)).match(/([\w]+)[\:\/\/]+([\w|\.]+)\//i);d.domain=a[2];h.addRuleKey("resolve","array").addRuleKey("stamp","object");var b={parseResolve:function(c){var a=d.resolve,e;if(a)for(var b=0,f=a.length;b<f&&!(e=a[b](c.id),e!==c.id);b++);
c.url=k.test(e)?e:d.protocol+"://"+d.domain+e},addFileSuffix:function(c){j.test(c.url)||(c.url+=".js")},addStamp:function(c){var a=d.hasStamp?l:null,b=d.stamp;b&&b[c.id]&&(a=b[c.id]);a&&(c.url+="?lofty.stamp="+a)},idToUrl:function(a){a.id||(a.id=a.url,f.emit("alias",a),b.parseResolve(a),b.addFileSuffix(a),b.addStamp(a))}};f.on("request",b.idToUrl);return b});
lofty("request",["cache","event","loader","global"],function(e,f,k,l){var g=e.config,h=e.assets={};g.loadTimeout=1E4;var j=function(b,c){if(!b.timeout){l.clearTimeout(b.timer);var d,a;c?(b.status=2,a=b.callQueue):(b.status=-1,a=b.errorQueue);for(;d=a.shift();)d()}};return function(b,c,d){var a;b={url:b};f.emit("request",b);a=h[b.url]||(h[b.url]=b);2===a.status?c&&c():(a.callQueue?a.callQueue.push(c):a.callQueue=[c],a.errorQueue?a.errorQueue.push(d):a.errorQueue=[d],1!==a.status&&(a.status=1,a.timer=
setTimeout(function(){a.timeout=!0;j(a,!1);f.emit("requestTimeout",a)},g.loadTimeout),k(a.url,function(){j(a,!0)})))}});
lofty("deferred",["lang"],function(c){var j=function(){},k=function(a){var e=this,f=[],g=0,d=0;a=a||1;var h=function(){e.then=!d?function(a){a&&a()}:function(a,b){b&&b()};h=j;c(!d?0:1);c=j;f=[]},c=function(a){for(var b,c=0;b=f[c++];)(b=b[a])&&b()};this.then=function(a,b){f.push([a,b])};this.resolve=function(){g++;g+d===a&&h()};this.reject=function(){d++;g+d===a&&h()}};return function(){var a=c.slice.call(arguments,0),e=new k(a.length);c.forEach(a,function(a){a(e)});return e}});
lofty("asyncrequire",["lang","event","module","request","deferred"],function(c,f,d,g,h){var a={fetch:function(b,a,j){h.apply(null,c.map(b,function(b){return function(a){d.has(b)?a.resolve():g(b,function(){a.resolve()},function(){a.reject()})}})).then(a,j)}};a.loader=a.fetch;a.realize=function(b,e){c.isArray(b)||(b=[b]);a.loader(b,function(){var a=c.map(b,function(a){return d.require(a)});e&&e.apply(null,a)})};f.on("makeRequire",function(b){b.async=function(b,c,d){a.realize(b,c,d)}});return a});
lofty("alicn",["cache","global","event"],function(a,d,e){a=a.config;var f=/\.css(?:\?|$)/;a.hasStamp=!0;a.resolve=[function(b){var a=b.split("/"),d=a[0],c=f.test(b)?"css":"js";switch(d){case "lofty":case "makeup":b="/fdevlib/"+c+b;break;case "sys":b="/sys/"+c+a.slice(1)}return b}];var c=!1;-1<d.location.search.indexOf("lofty.debug=")&&(c=!0);a.debug=c;this.appframe=function(a){d[a]={log:this.log,define:this.define,on:e.on}}});
