/*! Lofty v0.1 beta AIO http://lofty.fangdeng.org/ MIT*/
(function(c){if(!c.lofty){var f={},a=function(g,d,e){if(!f[g]){e||(e=d,d=[]);if("function"===typeof e){for(var h=[],l=0,c=d.length;l<c;l++)h.push(f[d[l]]);e=e.apply(a,h)}f[g]=e}},h=function(a){return f[a]};a.version="0.1";a.cache={kernel:f};a("global",c);a("require",function(){return h});c.lofty=a}})(this);
lofty("lang",function(){var c={}.toString,f=Array.prototype,a={isFunction:function(a){return"[object Function]"===c.call(a)},isArray:Array.isArray||function(a){return"[object Array]"===c.call(a)},isString:function(a){return"string"===typeof a},forEach:f.forEach?function(a,g,d){a.forEach(g,d)}:function(a,g,d){for(var e=0,c=a.length;e<c;e++)g.call(d,a[e],e,a)},map:f.map?function(a,g,d){return a.map(g,d)}:function(c,g,d){var e=[];a.forEach(c,function(a,l,c){e.push(g.call(d,a,l,c))});return e},indexOf:f.indexOf?
function(a,c){return a.indexOf(c)}:function(a,c){for(var d=0,e=a.length;d<e;d++)if(a[d]===c)return d;return-1}};return a});lofty("event",function(){var c=this.cache.events={},f=[].slice;return{on:function(a,f){(c[a]||(c[a]=[])).push(f)},emit:function(a){var h=f.call(arguments,1),g=c[a],d,e=0;if(g)for(;d=g[e++];)d.apply(null,h)}}});
lofty("config",["lang"],function(c){var f=this.cache,a=f.config={},h=f.configRules={},f={addRule:function(a,d){h[a]={rule:d,keys:[]};return this},addItem:function(a,d){h[d]&&h[d].keys.push(a);return this}};f.addRule("object",function(a,d,c){if(a){for(var f in c)a[f]=c[f];return!0}return!1}).addRule("array",function(a,d,c){a?a.push(c):this[d]=[c];return!0});this.config=function(f){for(var d in f){var e=f[d],j=a[d],l=d,m=e,k=!1,b=void 0,n=void 0;for(n in h)if(k)break;else b=h[n],k=-1<c.indexOf(b.keys,
l)&&b.rule.call(a,j,l,m);k||(a[d]=e)}};return f});lofty("alias",["config","event"],function(c,f){var a=this.cache.config;c.addItem("alias","object");return function(c){var g=a.alias,d;if(g&&(d=g[c.id]))c.id=d;f.emit("alias",c)}});
lofty("module",["global","lang","event","alias"],function(c,f,a,h){var g=[],d=0,e=this.cache.modules={},j={get:function(b){b={id:b};h(b);return e[b.id]},has:function(b){return j.get(b)||m[b]?!0:!1},hasDefine:function(b){return e[b]?!0:!1},isAnon:function(b){return""===b.id},save:function(b){e[b._id||b.id]=b},autocompile:function(b){j.isAnon(b)&&j.compile(b)},compile:function(b){try{if(f.isFunction(b.factory)){var c=[],d=b.deps;f.isArray(d)&&f.forEach(d,function(a){var d;a=(d=m[a])?d(b):j.require(a,
b);c.push(a)});var l=b.factory.apply(null,c);void 0!==l?b.exports=l:b.entity&&b.entity.exports&&(b.exports=b.entity.exports);b.entity&&delete b.entity}else void 0!==b.factory&&(b.exports=b.factory);a.emit("compiled",b)}catch(e){a.emit("compileFail",e,b)}},require:function(b){var d=j.get(b);d?(d.visits||(d.visits++,j.compile(d)),a.emit("required",d),b=d.exports):(a.emit("requireFail",{id:b}),b=null);return b}},l=function(b,a,c){this.id=b;this.deps=a||[];this.factory=c;this.exports={};this.visits=0;
""===b&&(b="__!_lofty_anonymous_"+d,d++,this._id=b)},m={require:function(){function b(b){return j.require(b)}a.emit("makeRequire",b);return b},exports:function(b){return b.exports},module:function(b){b.entity={id:b.id,exports:b.exports};return b.entity}},k=c.define;this.noConflict=function(){c.define=k};this.define=function(b,d,c){var e;e=arguments.length;1===e?(c=b,b=""):2===e&&(c=d,d=g,f.isString(b)||(d=b,b=""));if(j.hasDefine(b))return a.emit("existed",{id:b}),null;e=new l(b,d,c);a.emit("define",
e);j.save(e);j.autocompile(e)};c.define=this.define;return j});
lofty("loader",["global"],function(c){var f=this.cache.config,a=c.document,h=/\.css(?:\?|$)/,g=/loaded|complete|undefined/,d=536>1*c.navigator.userAgent.replace(/.*AppleWebKit\/(\d+)\..*/,"$1"),e=a&&(a.head||a.getElementsByTagName("head")[0]||a.documentElement),j=a.getElementsByTagName("base")[0],l=function(a,d){a.onerror=function(){a.onload=a.onreadystatechange=a.onerror=null;a=void 0;d&&d()}};return function(m,k){var b;if(h.test(m)){var n=b=a.createElement("link");if(d||!("onload"in n)){var q=a.createElement("img");
q.onerror=function(){k();q.onerror=null;q=void 0};q.src=m}else n.onload=n.onreadystatechange=function(){g.test(n.readyState)&&(n.onload=n.onreadystatechange=n.onerror=null,n=void 0,k&&k())},l(n,k);b.rel="stylesheet";b.href=m}else{var p=b=a.createElement("script");p.onload=p.onreadystatechange=function(b){b=b||c.event;if("load"===b.type||g.test(p.readyState))p.onload=p.onreadystatechange=p.onerror=null,f.debug||e.removeChild(p),p=void 0,k&&k()};l(p,k);b.async=!0;b.src=m}f.charset&&(b.charset=f.charset);
j?e.insertBefore(b,j):e.appendChild(b)}});
lofty("id2url",["global","event","config","alias"],function(c,f,a,h){var g=this.cache.config,d=/\?|\.(?:css|js)$|\/$/,e=/^https?:\/\//,j=(new Date).getTime();c=c.document.getElementsByTagName("script");c=c[c.length-1];c=(c.hasAttribute?c.src:c.getAttribute("src",4)).match(/([\w]+)\:\/\/([\w|\.|\:]+)\//i);g.baseUrl=c[0];a.addItem("resolve","array").addItem("stamp","object");return function(a){h(a);var c=g.resolve,k;if(c)for(var b=0,n=c.length;b<n&&!(k=c[b](a.id),k!==a.id);b++);a.url=k?k:a.id;f.emit("resolve",
a);e.test(a.url)||(a.url=g.baseUrl+a.url);!d.test(a.url)&&(a.url+=".js");c=g.hasStamp?j:null;if(k=g.stamp)for(var q in k)if(RegExp(q).test(a.id)){c=k[q];break}c&&(a.url+="?lofty.stamp="+c);f.emit("id2url",a)}});
lofty("request",["global","event","loader","id2url"],function(c,f,a,h){var g=this.cache,d=g.config,e=g.assets={};d.loadTimeout=1E4;var j=function(a,d){if(!a.timeout){c.clearTimeout(a.timer);var e,b;d?(a.status=2,b=a.callQueue):(a.status=-1,b=a.errorQueue);for(;e=b.shift();)e()}};return function(c,g,k){var b;c={id:c};h(c);b=e[c.url]||(e[c.url]=c);2===b.status?g&&g():(b.callQueue?b.callQueue.push(g):b.callQueue=[g],b.errorQueue?b.errorQueue.push(k):b.errorQueue=[k],1!==b.status&&(b.status=1,b.timer=
setTimeout(function(){b.timeout=!0;j(b,!1);f.emit("requestTimeout",b)},d.loadTimeout),a(b.url,function(){j(b,!0)})))}});
lofty("deferred",function(){var c=function(){},f=function(a){var f=this,g=[],d=0,e=0;a=a||0;var j=function(){d+e===a&&l()},l=function(){f.then=!e?function(a){a&&a()}:function(a,b){b&&b()};l=c;m(!e?0:1);m=c;g=[]},m=function(a){for(var b,c=0;b=g[c++];)(b=b[a])&&b()};this.then=function(a,b){g.push([a,b])};this.resolve=function(){d++;j()};this.reject=function(){e++;j()};j()};return function(){for(var a=new f(arguments.length),c,g=0;c=arguments[g++];)c(a);return a}});
lofty("use",["lang","event","module","request","deferred"],function(c,f,a,h,g){var d={load:function(e,f){c.isArray(e)||(e=[e]);d.fetch(e,function(){var d=c.map(e,function(c){return a.require(c)});f&&f.apply(null,d)})},fetch:function(e,f){d.get(e,function(){g.apply(null,c.map(e,function(c){return function(e){var f=a.get(c);f?d.fetch(f.deps,function(){e.resolve()}):e.resolve()}})).then(f)})},get:function(d,f,l){g.apply(null,c.map(d,function(c){return function(d){a.has(c)?d.resolve():h(c,function(){d.resolve()},
function(){d.reject()})}})).then(f,l)}};f.on("makeRequire",function(a){a.use=function(a,c,e){d.load(a,c,e)}});return d});lofty("amd",["module","use"],function(c,f){var a=this.cache.config;a.amd=!0;c.autocompile=function(h){c.isAnon(h)&&(a.amd?f.load(h.deps,function(){c.compile(h)}):c.compile(h))}});
lofty("debug",["global","config","console","request","require"],function(c,f,a,h,g){var d=this,e=this.log=function(){};f.addRule("debug",function(f,l,m){d.log=m?c.console?function(a,b){c.console[b||"log"](a)}:function(c,b){a?a(c,b):h&&h("lofty/kernel/console",function(){a||(a=g("console"));a(c,b)})}:e;this[l]=m;return!0}).addItem("debug","debug")});
lofty("alicn",["global","event","config"],function(c,f,a){var h=/\.css(?:\?|$)/,g=/([a-z])([A-Z])/g;f.on("resolve",function(a){a.url=a.url.replace(g,function(a,c,d){return c+"-"+d}).toLowerCase()});this.config({hasStamp:!0,resolve:function(a){var c=a.split("/"),f=c[0],g=h.test(a)?"css/":"js/";switch(f){case "lofty":case "gallery":a="fdevlib/"+g+a;break;case "sys":a="sys/"+g+c.slice(1).join("/")}return a},debug:function(){var a=!1;0<c.location.href.indexOf("lofty.debug=true")&&(a=!0);return a}()});
this.appframe=function(d){d=(c[d]={define:this.define,log:this.log,config:this.config,on:f.on}).config;d.addRule=a.addRule;d.addItem=a.addItem}});
