/*! Lofty v0.1 beta AIO http://lofty.fangdeng.org/ MIT*/
(function(a){if(!a.lofty){var f={},b=function(d,g,e){if(!f[d]){e||(e=g,g=[]);d=f[d]={id:d,deps:g,factory:e};if("function"===typeof d.factory){g=[];e=d.deps;for(var a=0,m=e.length;a<m;a++)g.push(h(e[a]));d.exports=d.factory.apply(b,g)}else d.exports=d.factory;delete d.factory}},h=function(d){return(d=f[d])?d.exports:null};b.version="0.1";b.cache={kernel:f};b("global",a);b("require",function(){return h});a.lofty=b}})(this);
lofty("lang",function(){var a={}.toString,f=Array.prototype,b={isFunction:function(b){return"[object Function]"===a.call(b)},isArray:Array.isArray||function(b){return"[object Array]"===a.call(b)},isString:function(b){return"string"===typeof b},forEach:f.forEach?function(b,d,g){b.forEach(d,g)}:function(b,d,g){for(var e=0,a=b.length;e<a;e++)d.call(g,b[e],e,b)},map:f.map?function(b,d,g){return b.map(d,g)}:function(a,d,g){var e=[];b.forEach(a,function(b,a,l){e.push(d.call(g,b,a,l))});return e},indexOf:f.indexOf?
function(b,d){return b.indexOf(d)}:function(b,d){for(var a=0,e=b.length;a<e;a++)if(b[a]===d)return a;return-1}};return b});lofty("event",function(){var a=this.cache.events={},f=[].slice;return{on:function(b,f){(a[b]||(a[b]=[])).push(f)},emit:function(b){var h=f.call(arguments,1),d=a[b],g,e=0;if(d)for(;g=d[e++];)g.apply(null,h)}}});
lofty("config",["lang"],function(a){var f=this.cache,b=f.config={},h=f.configRules={},f={addRule:function(b,a){h[b]={rule:a,keys:[]};return this},addRuleKey:function(b,a){h[a]&&h[a].keys.push(b);return this}};f.addRule("object",function(b,a,e){if(b){for(var j in e)b[j]=e[j];return!0}return!1}).addRule("array",function(b,a,e){b?b.push(e):this[a]=[e];return!0});this.config=function(d){for(var g in d){var e=d[g],j=b[g],m=g,l=e,k=!1,c=void 0,f=void 0;for(f in h)if(k)break;else c=h[f],k=-1<a.indexOf(c.keys,
m)&&c.rule.call(b,j,m,l);k||(b[g]=e)}};return f});lofty("alias",["config","event"],function(a,f){var b=this.cache.config;a.addRuleKey("alias","object");return function(a){var d=b.alias,g;if(d&&(g=d[a.id]))a.id=g;f.emit("alias",a)}});
lofty("module",["global","lang","event","alias"],function(a,f,b,h){var d=[],g=0,e=this.cache.modules={},j={get:function(c){c={id:c};h(c);return e[c.id]},has:function(c){return j.get(c)||l[c]?!0:!1},hasDefine:function(c){return e[c]?!0:!1},isAnon:function(c){return""===c.id},save:function(c){e[c._id||c.id]=c},autocompile:function(c){j.isAnon(c)&&j.compile(c)},compile:function(c){try{if(f.isFunction(c.factory)){var a=[],d=c.deps;f.isArray(d)&&f.forEach(d,function(b){var d;b=(d=l[b])?d(c):j.require(b,
c);a.push(b)});var e=c.factory.apply(null,a);void 0!==e?c.exports=e:c.entity&&(c.exports=c.entity.exports);c.entity&&delete c.entity}else void 0!==c.factory&&(c.exports=c.factory);b.emit("compiled",c)}catch(m){b.emit("compileFail",m,c)}},require:function(c){var a=j.get(c);a?(a.visits||(a.visits++,j.compile(a)),b.emit("required",a),c=a.exports):(b.emit("requireFail",{id:c}),c=null);return c}},m=function(c,b,a){this.id=c;this.deps=b||[];this.factory=a;this.exports={};this.visits=0;""===c&&(c="__!_lofty_anonymous_"+
g,g++,this._id=c)},l={require:function(){function c(c){return j.require(c)}b.emit("makeRequire",c);return c},exports:function(c){return c.exports},module:function(c){c.entity={id:c.id,exports:c.exports};return c.entity}},k=a.define;this.noConflict=function(){a.define=k};this.define=function(c,a,e){var l;l=arguments.length;1===l?(e=c,c=""):2===l&&(e=a,a=d,f.isString(c)||(a=c,c=""));if(j.hasDefine(c))return b.emit("existed",{id:c}),null;l=new m(c,a,e);b.emit("define",l);j.save(l);j.autocompile(l)};
a.define=this.define;return j});
lofty("loader",["global"],function(a){var f=this.cache.config,b=a.document,h=/\.css(?:\?|$)/,d=/loaded|complete|undefined/,g=536>1*a.navigator.userAgent.replace(/.*AppleWebKit\/(\d+)\..*/,"$1"),e=b&&(b.head||b.getElementsByTagName("head")[0]||b.documentElement),j=b.getElementsByTagName("base")[0],m=function(b,a){b.onerror=function(){b.onload=b.onreadystatechange=b.onerror=null;b=void 0;a&&a()}};return function(l,k){var c;if(h.test(l)){var n=c=b.createElement("link");if(g||!("onload"in n)){var q=b.createElement("img");
q.onerror=function(){k();q.onerror=null;q=void 0};q.src=l}else n.onload=n.onreadystatechange=function(){d.test(n.readyState)&&(n.onload=n.onreadystatechange=n.onerror=null,n=void 0,k&&k())},m(n,k);c.rel="stylesheet";c.href=l}else{var p=c=b.createElement("script");p.onload=p.onreadystatechange=function(c){c=c||a.event;if("load"===c.type||d.test(p.readyState))p.onload=p.onreadystatechange=p.onerror=null,f.debug||e.removeChild(p),p=void 0,k&&k()};m(p,k);c.async=!0;c.src=l}f.charset&&(c.charset=f.charset);
j?e.insertBefore(c,j):e.appendChild(c)}});
lofty("id2url",["global","event","config","alias"],function(a,f,b,h){var d=this.cache.config,g=/\?|\.(?:css|js)$|\/$/,e=/^https?:\/\//,j=(new Date).getTime();a=a.document.getElementsByTagName("script");a=a[a.length-1];a=(a.hasAttribute?a.src:a.getAttribute("src",4)).match(/([\w]+)\:\/\/([\w|\.|\:]+)\//i);d.baseUrl=a[0];b.addRuleKey("resolve","array").addRuleKey("stamp","object");return function(b){h(b);var a=d.resolve,k;if(a)for(var c=0,n=a.length;c<n&&!(k=a[c](b.id),k!==b.id);c++);b.url=k?k:b.id;
e.test(b.url)||(b.url=d.baseUrl+b.url);!g.test(b.url)&&(b.url+=".js");a=d.hasStamp?j:null;if(k=d.stamp)for(var q in k)if(RegExp(q).test(b.id)){a=k[q];break}a&&(b.url+="?lofty.stamp="+a);f.emit("id2url",b)}});
lofty("request",["global","event","loader","id2url"],function(a,f,b,h){var d=this.cache,g=d.config,e=d.assets={};g.loadTimeout=1E4;var j=function(b,d){if(!b.timeout){a.clearTimeout(b.timer);var e,c;d?(b.status=2,c=b.callQueue):(b.status=-1,c=b.errorQueue);for(;e=c.shift();)e()}};return function(a,d,k){var c;a={id:a};h(a);c=e[a.url]||(e[a.url]=a);2===c.status?d&&d():(c.callQueue?c.callQueue.push(d):c.callQueue=[d],c.errorQueue?c.errorQueue.push(k):c.errorQueue=[k],1!==c.status&&(c.status=1,c.timer=
setTimeout(function(){c.timeout=!0;j(c,!1);f.emit("requestTimeout",c)},g.loadTimeout),b(c.url,function(){j(c,!0)})))}});
lofty("deferred",function(){var a=function(){},f=function(b){var f=this,d=[],g=0,e=0;b=b||1;var j=function(){f.then=!e?function(b){b&&b()}:function(b,a){a&&a()};j=a;m(!e?0:1);m=a;d=[]},m=function(b){for(var a,c=0;a=d[c++];)(a=a[b])&&a()};this.then=function(b,a){d.push([b,a])};this.resolve=function(){g++;g+e===b&&j()};this.reject=function(){e++;g+e===b&&j()}};return function(){for(var b=new f(arguments.length),a,d=0;a=arguments[d++];)a(b);return b}});
lofty("use",["lang","event","module","request","deferred"],function(a,f,b,h,d){var g={realize:function(d,f){a.isArray(d)||(d=[d]);g.load(d,function(){var g=a.map(d,function(a){return b.require(a)});f&&f.apply(null,g)})},load:function(d,f){var h=[];a.forEach(d,function(a){b.has(a)||h.push(a)});h.length?g.fetch(h,f):f()},fetch:function(e,f){g.get(e,function(){d.apply(null,a.map(e,function(a){return function(d){var e=b.get(a);e?g.load(e.deps,function(){d.resolve()}):d.resolve()}})).then(f)})},get:function(e,
f,g){d.apply(null,a.map(e,function(a){return function(d){b.has(a)?d.resolve():h(a,function(){d.resolve()},function(){d.reject()})}})).then(f,g)}};f.on("makeRequire",function(a){a.use=function(a,b,d){g.realize(a,b,d)}});return g});lofty("amd",["module","use"],function(a,f){var b=this.cache.config;b.amd=!0;a.autocompile=function(h){a.isAnon(h)&&(b.amd?f.load(h.deps,function(){a.compile(h)}):a.compile(h))}});
lofty("debug",["global","config","console","request","require"],function(a,f,b,h,d){var g=this,e=this.log=function(){};f.addRule("debug",function(f,m,l){g.log=l?a.console?function(b,c){a.console[c||"log"](b)}:function(a,c){b?b(a,c):h&&h("lofty/kernel/console",function(){b||(b=d("console"));b(a,c)})}:e;this[m]=l;return!0}).addRuleKey("debug","debug")});
lofty("alicn",["global","event"],function(a,f){var b=/\.css(?:\?|$)/,h=/([a-z])([A-Z])/g;this.config({hasStamp:!0,resolve:function(a){a=a.replace(h,function(a,b,d){return b+"-"+d}).toLowerCase();var f=a.split("/"),e=f[0],j=b.test(a)?"css/":"js/";switch(e){case "lofty":case "avid":a="/fdevlib/"+j+a;break;case "sys":a="/sys/"+j+f.slice(1).join("/")}return a},debug:function(){var b=!1;0<a.location.href.indexOf("lofty.debug=true")&&(b=!0);return b}()});this.appframe=function(b){a[b]={log:this.log,define:this.define,
on:f.on}}});
