/*! Lofty v0.1 beta Classic http://lofty.fangdeng.org/ MIT*/
(function(d){if(!d.lofty){var g={},a=function(b,f,e){if(!g[b]){e||(e=f,f=[]);b=g[b]={id:b,deps:f,factory:e};if("function"===typeof b.factory){f=[];e=b.deps;for(var h=0,l=e.length;h<l;h++)f.push(j(e[h]));b.exports=b.factory.apply(a,f)}else b.exports=b.factory;delete b.factory}},j=function(b){return(b=g[b])?b.exports:null};a.version="0.1";a.cache={kernel:g};a("global",d);a("require",function(){return j});d.lofty=a}})(this);
lofty("lang",function(){var d={}.toString,g=Array.prototype,a={isFunction:function(a){return"[object Function]"===d.call(a)},isArray:Array.isArray||function(a){return"[object Array]"===d.call(a)},isString:function(a){return"string"===typeof a},forEach:g.forEach?function(a,b,f){a.forEach(b,f)}:function(a,b,f){for(var e=0,h=a.length;e<h;e++)b.call(f,a[e],e,a)},map:g.map?function(a,b,f){return a.map(b,f)}:function(d,b,f){var e=[];a.forEach(d,function(a,l,m){e.push(b.call(f,a,l,m))});return e},indexOf:g.indexOf?
function(a,b){return a.indexOf(b)}:function(a,b){for(var f=0,e=a.length;f<e;f++)if(a[f]===b)return f;return-1}};return a});lofty("event",function(){var d=this.cache.events={},g=[].slice;return{on:function(a,g){(d[a]||(d[a]=[])).push(g)},emit:function(a){var j=g.call(arguments,1),b=d[a],f,e=0;if(b)for(;f=b[e++];)f.apply(null,j)}}});
lofty("config",["lang"],function(d){var g=this.cache,a=g.config={},j=g.configRules={},g={addRule:function(b,a){j[b]={rule:a,keys:[]};return this},addRuleKey:function(a,f){j[f]&&j[f].keys.push(a);return this}};g.addRule("object",function(a,f,e){if(a){for(var d in e)a[d]=e[d];return!0}return!1}).addRule("array",function(a,f,e){a?a.push(e):this[f]=[e];return!0});this.config=function(b){for(var f in b){var e=b[f],h=a[f],l=f,m=e,k=!1,c=void 0,g=void 0;for(g in j)if(k)break;else c=j[g],k=-1<d.indexOf(c.keys,
l)&&c.rule.call(a,h,l,m);k||(a[f]=e)}};return g});lofty("alias",["config","event"],function(d,g){var a=this.cache.config;d.addRuleKey("alias","object");return function(d){var b=a.alias,f;if(b&&(f=b[d.id]))d.id=f;g.emit("alias",d)}});
lofty("module",["global","lang","event","alias"],function(d,g,a,j){var b=[],f=0,e=this.cache.modules={},h={get:function(c){c={id:c};j(c);return e[c.id]},has:function(c){return h.get(c)||m[c]?!0:!1},hasDefine:function(c){return e[c]?!0:!1},isAnon:function(c){return""===c.id},save:function(c){e[c._id||c.id]=c},autocompile:function(c){h.isAnon(c)&&h.compile(c)},compile:function(c){try{if(g.isFunction(c.factory)){var b=[],e=c.deps;g.isArray(e)&&g.forEach(e,function(a){var e;a=(e=m[a])?e(c):h.require(a,
c);b.push(a)});var f=c.factory.apply(null,b);void 0!==f?c.exports=f:c.entity&&(c.exports=c.entity.exports);c.entity&&delete c.entity}else void 0!==c.factory&&(c.exports=c.factory);a.emit("compiled",c)}catch(d){a.emit("compileFail",d,c)}},require:function(c){var b=h.get(c);b?(b.visits||(b.visits++,h.compile(b)),a.emit("required",b),c=b.exports):(a.emit("requireFail",{id:c}),c=null);return c}},l=function(c,a,b){this.id=c;this.deps=a||[];this.factory=b;this.exports={};this.visits=0;""===c&&(c="__!_lofty_anonymous_"+
f,f++,this._id=c)},m={require:function(){function c(c){return h.require(c)}a.emit("makeRequire",c);return c},exports:function(c){return c.exports},module:function(c){c.entity={id:c.id,exports:c.exports};return c.entity}},k=d.define;this.noConflict=function(){d.define=k};this.define=function(c,e,f){var d;d=arguments.length;1===d?(f=c,c=""):2===d&&(f=e,e=b,g.isString(c)||(e=c,c=""));if(h.hasDefine(c))return a.emit("existed",{id:c}),null;d=new l(c,e,f);a.emit("define",d);h.save(d);h.autocompile(d)};
d.define=this.define;return h});
lofty("loader",["global"],function(d){var g=this.cache.config,a=d.document,j=/\.css(?:\?|$)/,b=/loaded|complete|undefined/,f=536>1*d.navigator.userAgent.replace(/.*AppleWebKit\/(\d+)\..*/,"$1"),e=a&&(a.head||a.getElementsByTagName("head")[0]||a.documentElement),h=a.getElementsByTagName("base")[0],l=function(a,b){a.onerror=function(){a.onload=a.onreadystatechange=a.onerror=null;a=void 0;b&&b()}};return function(m,k){var c;if(j.test(m)){var n=c=a.createElement("link");if(f||!("onload"in n)){var q=a.createElement("img");
q.onerror=function(){k();q.onerror=null;q=void 0};q.src=m}else n.onload=n.onreadystatechange=function(){b.test(n.readyState)&&(n.onload=n.onreadystatechange=n.onerror=null,n=void 0,k&&k())},l(n,k);c.rel="stylesheet";c.href=m}else{var p=c=a.createElement("script");p.onload=p.onreadystatechange=function(c){c=c||d.event;if("load"===c.type||b.test(p.readyState))p.onload=p.onreadystatechange=p.onerror=null,g.debug||e.removeChild(p),p=void 0,k&&k()};l(p,k);c.async=!0;c.src=m}g.charset&&(c.charset=g.charset);
h?e.insertBefore(c,h):e.appendChild(c)}});
lofty("id2url",["global","event","config","alias"],function(d,g,a,j){var b=this.cache.config,f=/\?|\.(?:css|js)$|\/$/,e=/^https?:\/\//,h=(new Date).getTime();d=d.document.getElementsByTagName("script");d=d[d.length-1];d=(d.hasAttribute?d.src:d.getAttribute("src",4)).match(/([\w]+)\:\/\/([\w|\.|\:]+)\//i);b.baseUrl=d[0];a.addRuleKey("resolve","array").addRuleKey("stamp","object");return function(a){j(a);var d=b.resolve,k;if(d)for(var c=0,n=d.length;c<n&&!(k=d[c](a.id),k!==a.id);c++);a.url=k?k:a.id;
e.test(a.url)||(a.url=b.baseUrl+a.url);!f.test(a.url)&&(a.url+=".js");d=b.hasStamp?h:null;if(k=b.stamp)for(var q in k)if(RegExp(q).test(a.id)){d=k[q];break}d&&(a.url+="?lofty.stamp="+d);g.emit("id2url",a)}});
lofty("request",["global","event","loader","id2url"],function(d,g,a,j){var b=this.cache,f=b.config,e=b.assets={};f.loadTimeout=1E4;var h=function(a,b){if(!a.timeout){d.clearTimeout(a.timer);var e,c;b?(a.status=2,c=a.callQueue):(a.status=-1,c=a.errorQueue);for(;e=c.shift();)e()}};return function(b,d,k){var c;b={id:b};j(b);c=e[b.url]||(e[b.url]=b);2===c.status?d&&d():(c.callQueue?c.callQueue.push(d):c.callQueue=[d],c.errorQueue?c.errorQueue.push(k):c.errorQueue=[k],1!==c.status&&(c.status=1,c.timer=
setTimeout(function(){c.timeout=!0;h(c,!1);g.emit("requestTimeout",c)},f.loadTimeout),a(c.url,function(){h(c,!0)})))}});
lofty("deferred",function(){var d=function(){},g=function(a){var g=this,b=[],f=0,e=0;a=a||1;var h=function(){g.then=!e?function(a){a&&a()}:function(a,b){b&&b()};h=d;l(!e?0:1);l=d;b=[]},l=function(a){for(var d,c=0;d=b[c++];)(d=d[a])&&d()};this.then=function(a,d){b.push([a,d])};this.resolve=function(){f++;f+e===a&&h()};this.reject=function(){e++;f+e===a&&h()}};return function(){for(var a=new g(arguments.length),d,b=0;d=arguments[b++];)d(a);return a}});
lofty("use",["lang","event","module","request","deferred"],function(d,g,a,j,b){var f={realize:function(b,h){d.isArray(b)||(b=[b]);f.load(b,function(){var f=d.map(b,function(b){return a.require(b)});h&&h.apply(null,f)})},load:function(b,h){var g=[];d.forEach(b,function(b){a.has(b)||g.push(b)});g.length?f.fetch(g,h):h()},fetch:function(e,g){f.get(e,function(){b.apply(null,d.map(e,function(b){return function(d){var e=a.get(b);e?f.load(e.deps,function(){d.resolve()}):d.resolve()}})).then(g)})},get:function(e,
f,g){b.apply(null,d.map(e,function(b){return function(d){a.has(b)?d.resolve():j(b,function(){d.resolve()},function(){d.reject()})}})).then(f,g)}};g.on("makeRequire",function(a){a.use=function(a,b,d){f.realize(a,b,d)}});return f});
lofty("debug",["global","config","console","request","require"],function(d,g,a,j,b){var f=this,e=this.log=function(){};g.addRule("debug",function(g,l,m){f.log=m?d.console?function(a,b){d.console[b||"log"](a)}:function(d,c){a?a(d,c):j&&j("lofty/kernel/console",function(){a||(a=b("console"));a(d,c)})}:e;this[l]=m;return!0}).addRuleKey("debug","debug")});
lofty("alicn",["global","event"],function(d,g){var a=/\.css(?:\?|$)/,j=/([a-z])([A-Z])/g;this.config({hasStamp:!0,resolve:function(b){b=b.replace(j,function(a,b,d){return b+"-"+d}).toLowerCase();var d=b.split("/"),e=d[0],g=a.test(b)?"css/":"js/";switch(e){case "lofty":case "avid":b="/fdevlib/"+g+b;break;case "sys":b="/sys/"+g+d.slice(1).join("/")}return b},debug:function(){var a=!1;0<d.location.href.indexOf("lofty.debug=true")&&(a=!0);return a}()});this.appframe=function(a){d[a]={log:this.log,define:this.define,
on:g.on}}});
