/*! Lofty v0.1 beta Classic http://lofty.fangdeng.org/ MIT*/
(function(c){if(!c.lofty){var g={},a=function(f,d,e){if(!g[f]){e||(e=d,d=[]);if("function"===typeof e){for(var h=[],l=0,m=d.length;l<m;l++)h.push(g[d[l]]);e=e.apply(a,h)}g[f]=e}},h=function(f){return g[f]};a.version="0.1";a.cache={kernel:g};a("global",c);a("require",function(){return h});c.lofty=a}})(this);
lofty("lang",function(){var c={}.toString,g=Array.prototype,a={isFunction:function(a){return"[object Function]"===c.call(a)},isArray:Array.isArray||function(a){return"[object Array]"===c.call(a)},isString:function(a){return"string"===typeof a},forEach:g.forEach?function(a,f,d){a.forEach(f,d)}:function(a,f,d){for(var e=0,c=a.length;e<c;e++)f.call(d,a[e],e,a)},map:g.map?function(a,f,d){return a.map(f,d)}:function(c,f,d){var e=[];a.forEach(c,function(a,l,c){e.push(f.call(d,a,l,c))});return e},indexOf:g.indexOf?
function(a,f){return a.indexOf(f)}:function(a,f){for(var d=0,e=a.length;d<e;d++)if(a[d]===f)return d;return-1}};return a});lofty("event",function(){var c=this.cache.events={},g=[].slice;return{on:function(a,g){(c[a]||(c[a]=[])).push(g)},emit:function(a){var h=g.call(arguments,1),f=c[a],d,e=0;if(f)for(;d=f[e++];)d.apply(null,h)}}});
lofty("config",["lang"],function(c){var g=this.cache,a=g.config={},h=g.configRules={},g={addRule:function(a,d){h[a]={rule:d,keys:[]};return this},addItem:function(a,d){h[d]&&h[d].keys.push(a);return this}};g.addRule("object",function(a,d,e){if(a){for(var c in e)a[c]=e[c];return!0}return!1}).addRule("array",function(a,d,e){a?a.push(e):this[d]=[e];return!0});this.config=function(f){for(var d in f){var e=f[d],g=a[d],l=d,m=e,j=!1,b=void 0,n=void 0;for(n in h)if(j)break;else b=h[n],j=-1<c.indexOf(b.keys,
l)&&b.rule.call(a,g,l,m);j||(a[d]=e)}};return g});lofty("alias",["config","event"],function(c,g){var a=this.cache.config;c.addItem("alias","object");return function(c){var f=a.alias,d;if(f&&(d=f[c.id]))c.id=d;g.emit("alias",c)}});
lofty("module",["global","lang","event","alias"],function(c,g,a,h){var f=[],d=0,e=this.cache.modules={},k={get:function(b){b={id:b};h(b);return e[b.id]},has:function(b){return k.get(b)||m[b]?!0:!1},hasDefine:function(b){return e[b]?!0:!1},isAnon:function(b){return""===b.id},save:function(b){e[b._id||b.id]=b},autocompile:function(b){k.isAnon(b)&&k.compile(b)},compile:function(b){try{if(g.isFunction(b.factory)){var d=[],e=b.deps;g.isArray(e)&&g.forEach(e,function(a){var e;a=(e=m[a])?e(b):k.require(a,
b);d.push(a)});var c=b.factory.apply(null,d);void 0!==c?b.exports=c:b.entity&&b.entity.exports&&(b.exports=b.entity.exports);b.entity&&delete b.entity}else void 0!==b.factory&&(b.exports=b.factory);a.emit("compiled",b)}catch(l){a.emit("compileFail",l,b)}},require:function(b){var d=k.get(b);d?(d.visits||(d.visits++,k.compile(d)),a.emit("required",d),b=d.exports):(a.emit("requireFail",{id:b}),b=null);return b}},l=function(b,a,e){this.id=b;this.deps=a||[];this.factory=e;this.exports={};this.visits=0;
""===b&&(b="__!_lofty_anonymous_"+d,d++,this._id=b)},m={require:function(){function b(b){return k.require(b)}a.emit("makeRequire",b);return b},exports:function(b){return b.exports},module:function(b){b.entity={id:b.id,exports:b.exports};return b.entity}},j=c.define;this.noConflict=function(){c.define=j};this.define=function(b,d,e){var c;c=arguments.length;1===c?(e=b,b=""):2===c&&(e=d,d=f,g.isString(b)||(d=b,b=""));if(k.hasDefine(b))return a.emit("existed",{id:b}),null;c=new l(b,d,e);a.emit("define",
c);k.save(c);k.autocompile(c)};c.define=this.define;return k});
lofty("loader",["global"],function(c){var g=this.cache.config,a=c.document,h=/\.css(?:\?|$)/,f=/loaded|complete|undefined/,d=536>1*c.navigator.userAgent.replace(/.*AppleWebKit\/(\d+)\..*/,"$1"),e=a&&(a.head||a.getElementsByTagName("head")[0]||a.documentElement),k=a.getElementsByTagName("base")[0],l=function(a,d){a.onerror=function(){a.onload=a.onreadystatechange=a.onerror=null;a=void 0;d&&d()}};return function(m,j){var b;if(h.test(m)){var n=b=a.createElement("link");if(d||!("onload"in n)){var q=a.createElement("img");
q.onerror=function(){j();q.onerror=null;q=void 0};q.src=m}else n.onload=n.onreadystatechange=function(){f.test(n.readyState)&&(n.onload=n.onreadystatechange=n.onerror=null,n=void 0,j&&j())},l(n,j);b.rel="stylesheet";b.href=m}else{var p=b=a.createElement("script");p.onload=p.onreadystatechange=function(b){b=b||c.event;if("load"===b.type||f.test(p.readyState))p.onload=p.onreadystatechange=p.onerror=null,g.debug||e.removeChild(p),p=void 0,j&&j()};l(p,j);b.async=!0;b.src=m}g.charset&&(b.charset=g.charset);
k?e.insertBefore(b,k):e.appendChild(b)}});
lofty("id2url",["global","event","config","alias"],function(c,g,a,h){var f=this.cache.config,d=/\?|\.(?:css|js)$|\/$/,e=/^https?:\/\//,k=(new Date).getTime();c=c.document.getElementsByTagName("script");c=c[c.length-1];c=(c.hasAttribute?c.src:c.getAttribute("src",4)).match(/([\w]+)\:\/\/([\w|\.|\:]+)\//i);f.baseUrl=c[0];a.addItem("resolve","array").addItem("stamp","object");return function(a){h(a);var c=f.resolve,j;if(c)for(var b=0,n=c.length;b<n&&!(j=c[b](a.id),j!==a.id);b++);a.url=j?j:a.id;g.emit("resolve",
a);e.test(a.url)||(a.url=f.baseUrl+a.url);!d.test(a.url)&&(a.url+=".js");c=f.hasStamp?k:null;if(j=f.stamp)for(var q in j)if(RegExp(q).test(a.id)){c=j[q];break}c&&(a.url+="?lofty.stamp="+c);g.emit("id2url",a)}});
lofty("request",["global","event","loader","id2url"],function(c,g,a,h){var f=this.cache,d=f.config,e=f.assets={};d.loadTimeout=1E4;var k=function(a,d){if(!a.timeout){c.clearTimeout(a.timer);var e,b;d?(a.status=2,b=a.callQueue):(a.status=-1,b=a.errorQueue);for(;e=b.shift();)e()}};return function(c,f,j){var b;c={id:c};h(c);b=e[c.url]||(e[c.url]=c);2===b.status?f&&f():(b.callQueue?b.callQueue.push(f):b.callQueue=[f],b.errorQueue?b.errorQueue.push(j):b.errorQueue=[j],1!==b.status&&(b.status=1,b.timer=
setTimeout(function(){b.timeout=!0;k(b,!1);g.emit("requestTimeout",b)},d.loadTimeout),a(b.url,function(){k(b,!0)})))}});
lofty("deferred",function(){var c=function(){},g=function(a){var g=this,f=[],d=0,e=0;a=a||0;var k=function(){d+e===a&&l()},l=function(){g.then=!e?function(a){a&&a()}:function(a,b){b&&b()};l=c;m(!e?0:1);m=c;f=[]},m=function(a){for(var b,d=0;b=f[d++];)(b=b[a])&&b()};this.then=function(a,b){f.push([a,b])};this.resolve=function(){d++;k()};this.reject=function(){e++;k()};k()};return function(){for(var a=new g(arguments.length),c,f=0;c=arguments[f++];)c(a);return a}});
lofty("use",["lang","event","module","request","deferred"],function(c,g,a,h,f){var d={load:function(e,f){c.isArray(e)||(e=[e]);d.fetch(e,function(){var d=c.map(e,function(d){return a.require(d)});f&&f.apply(null,d)})},fetch:function(e,g){d.get(e,function(){f.apply(null,c.map(e,function(c){return function(e){var f=a.get(c);f?d.fetch(f.deps,function(){e.resolve()}):e.resolve()}})).then(g)})},get:function(d,g,l){f.apply(null,c.map(d,function(d){return function(c){a.has(d)?c.resolve():h(d,function(){c.resolve()},
function(){c.reject()})}})).then(g,l)}};g.on("makeRequire",function(a){a.use=function(a,c,e){d.load(a,c,e)}});return d});lofty("debug",["global","config","console","request","require"],function(c,g,a,h,f){var d=this,e=this.log=function(){};g.addRule("debug",function(g,l,m){d.log=m?c.console?function(a,b){c.console[b||"log"](a)}:function(d,b){a?a(d,b):h&&h("lofty/kernel/console",function(){a||(a=f("console"));a(d,b)})}:e;this[l]=m;return!0}).addItem("debug","debug")});
lofty("alicn",["global","event","config"],function(c,g,a){var h=/\.css(?:\?|$)/,f=/([a-z])([A-Z])/g;g.on("resolve",function(a){a.url=a.url.replace(f,function(a,d,c){return d+"-"+c}).toLowerCase()});this.config({hasStamp:!0,resolve:function(a){var c=a.split("/"),f=c[0],g=h.test(a)?"css/":"js/";switch(f){case "lofty":case "gallery":a="fdevlib/"+g+a;break;case "sys":a="sys/"+g+c.slice(1).join("/")}return a},debug:function(){var a=!1;0<c.location.href.indexOf("lofty.debug=true")&&(a=!0);return a}()});
this.appframe=function(d){d=(c[d]={define:this.define,log:this.log,config:this.config,on:g.on}).config;d.addRule=a.addRule;d.addItem=a.addItem}});
