/*! Lofty v0.1 beta Starter http://lofty.fangdeng.org/ MIT*/
(function(f){if(!f.lofty){var g={},c=function(d,a,h){if(!g[d]){h||(h=a,a=[]);d=g[d]={id:d,deps:a,factory:h};if("function"===typeof d.factory){a=[];h=d.deps;for(var j=0,f=h.length;j<f;j++)a.push(e(h[j]));d.exports=d.factory.apply(c,a)}else d.exports=d.factory;delete d.factory}},e=function(d){return(d=g[d])?d.exports:null};c.version="0.1";c.cache={kernel:g};c("global",f);c("require",function(){return e});f.lofty=c}})(this);
lofty("lang",function(){var f={}.toString,g=Array.prototype,c={isFunction:function(e){return"[object Function]"===f.call(e)},isArray:Array.isArray||function(e){return"[object Array]"===f.call(e)},isString:function(e){return"string"===typeof e},forEach:g.forEach?function(e,d,a){e.forEach(d,a)}:function(e,d,a){for(var c=0,j=e.length;c<j;c++)d.call(a,e[c],c,e)},map:g.map?function(c,d,a){return c.map(d,a)}:function(e,d,a){var h=[];c.forEach(e,function(c,e,f){h.push(d.call(a,c,e,f))});return h},indexOf:g.indexOf?
function(c,d){return c.indexOf(d)}:function(c,d){for(var a=0,h=c.length;a<h;a++)if(c[a]===d)return a;return-1}};return c});lofty("event",function(){var f=this.cache.events={},g=[].slice;return{on:function(c,e){(f[c]||(f[c]=[])).push(e)},emit:function(c){var e=g.call(arguments,1),d=f[c],a,h=0;if(d)for(;a=d[h++];)a.apply(null,e)}}});
lofty("config",["lang"],function(f){var g=this.cache,c=g.config={},e=g.configRules={},g={addRule:function(d,a){e[d]={rule:a,keys:[]};return this},addItem:function(d,a){e[a]&&e[a].keys.push(d);return this}};g.addRule("object",function(d,a,c){if(d){for(var e in c)d[e]=c[e];return!0}return!1}).addRule("array",function(c,a,e){c?c.push(e):this[a]=[e];return!0});this.config=function(d){for(var a in d){var g=d[a],j=c[a],m=a,l=g,k=!1,b=void 0,n=void 0;for(n in e)if(k)break;else b=e[n],k=-1<f.indexOf(b.keys,
m)&&b.rule.call(c,j,m,l);k||(c[a]=g)}};return g});lofty("alias",["config","event"],function(f,g){var c=this.cache.config;f.addItem("alias","object");return function(e){var d=c.alias,a;if(d&&(a=d[e.id]))e.id=a;g.emit("alias",e)}});
lofty("module",["global","lang","event","alias"],function(f,g,c,e){var d=[],a=0,h=this.cache.modules={},j={get:function(b){b={id:b};e(b);return h[b.id]},has:function(b){return j.get(b)||l[b]?!0:!1},hasDefine:function(b){return h[b]?!0:!1},isAnon:function(b){return""===b.id},save:function(b){h[b._id||b.id]=b},autocompile:function(b){j.isAnon(b)&&j.compile(b)},compile:function(b){try{if(g.isFunction(b.factory)){var a=[],d=b.deps;g.isArray(d)&&g.forEach(d,function(c){var d;c=(d=l[c])?d(b):j.require(c,
b);a.push(c)});var e=b.factory.apply(null,a);void 0!==e?b.exports=e:b.entity&&b.entity.exports&&(b.exports=b.entity.exports);b.entity&&delete b.entity}else void 0!==b.factory&&(b.exports=b.factory);c.emit("compiled",b)}catch(f){c.emit("compileFail",f,b)}},require:function(b){var a=j.get(b);a?(a.visits||(a.visits++,j.compile(a)),c.emit("required",a),b=a.exports):(c.emit("requireFail",{id:b}),b=null);return b}},m=function(b,c,d){this.id=b;this.deps=c||[];this.factory=d;this.exports={};this.visits=0;
""===b&&(b="__!_lofty_anonymous_"+a,a++,this._id=b)},l={require:function(){function b(b){return j.require(b)}c.emit("makeRequire",b);return b},exports:function(b){return b.exports},module:function(b){b.entity={id:b.id,exports:b.exports};return b.entity}},k=f.define;this.noConflict=function(){f.define=k};this.define=function(b,a,e){var f;f=arguments.length;1===f?(e=b,b=""):2===f&&(e=a,a=d,g.isString(b)||(a=b,b=""));if(j.hasDefine(b))return c.emit("existed",{id:b}),null;f=new m(b,a,e);c.emit("define",
f);j.save(f);j.autocompile(f)};f.define=this.define;return j});
lofty("console",["global","lang"],function(f,g){var c=f.document,e=[],d=null,a=!1,h=function(a){var e=c.createElement("li");e.style.color="warn"===a.type?"red":"#000";e.innerHTML=a.message;d.appendChild(e)},j=function(a){c.body?(c.body.appendChild(a),d=c.createElement("ol"),d.style.listStyleType="decimal",a.appendChild(d),g.forEach(e,function(a){h(a)})):f.setTimeout(function(){j(a)},200)};return function(f,g){var k={message:f,type:g||"log"};if(!a){var b=c.createElement("div");b.id="lofty-debug-console";
b.style.margin="10px 0";b.style.border="1px dashed red";b.style.padding="4px 8px";b.style.fontSize="14px";b.style.lineHeight="1.5";b.style.textAlign="left";j(b);a=!0}d?h(k):e.push(k)}});
lofty("debug",["global","config","console","request","require"],function(f,g,c,e,d){var a=this,h=this.log=function(){};g.addRule("debug",function(g,m,l){a.log=l?f.console?function(a,b){f.console[b||"log"](a)}:function(a,b){c?c(a,b):e&&e("lofty/kernel/console",function(){c||(c=d("console"));c(a,b)})}:h;this[m]=l;return!0}).addItem("debug","debug")});
lofty("alicn",["global","event","config"],function(f,g,c){var e=/\.css(?:\?|$)/,d=/([a-z])([A-Z])/g;this.config({hasStamp:!0,resolve:function(a){a=a.replace(d,function(a,c,b){return c+"-"+b}).toLowerCase();var c=a.split("/"),f=c[0],g=e.test(a)?"css/":"js/";switch(f){case "lofty":case "avid":a="/fdevlib/"+g+a;break;case "sys":a="/sys/"+g+c.slice(1).join("/")}return a},debug:function(){var a=!1;0<f.location.href.indexOf("lofty.debug=true")&&(a=!0);return a}()});this.appframe=function(a){a=f[a]={define:this.define,
log:this.log,config:this.config,on:g.on};a.config.addRule=c.addRule;a.config.addItem=c.addItem}});
