/*! Lofty v0.1 beta Starter http://lofty.fangdeng.org/ MIT*/
(function(f){if(!f.lofty){var g={},c=function(a,e,h){if(!g[a]){h||(h=e,e=[]);a=g[a]={id:a,deps:e,factory:h};if("function"===typeof a.factory){e=[];h=a.deps;for(var j=0,f=h.length;j<f;j++)e.push(d(h[j]));a.exports=a.factory.apply(c,e)}else a.exports=a.factory;delete a.factory}},d=function(a){return(a=g[a])?a.exports:null};c.version="0.1";c.cache={kernel:g};c("global",f);c("require",function(){return d});f.lofty=c}})(this);
lofty("lang",function(){var f={}.toString,g=Array.prototype,c={isFunction:function(d){return"[object Function]"===f.call(d)},isArray:Array.isArray||function(d){return"[object Array]"===f.call(d)},isString:function(d){return"string"===typeof d},forEach:g.forEach?function(d,a,e){d.forEach(a,e)}:function(d,a,e){for(var c=0,j=d.length;c<j;c++)a.call(e,d[c],c,d)},map:g.map?function(c,a,e){return c.map(a,e)}:function(d,a,e){var h=[];c.forEach(d,function(c,d,f){h.push(a.call(e,c,d,f))});return h},indexOf:g.indexOf?
function(c,a){return c.indexOf(a)}:function(c,a){for(var e=0,h=c.length;e<h;e++)if(c[e]===a)return e;return-1}};return c});lofty("event",function(){var f=this.cache.events={},g=[].slice;return{on:function(c,d){(f[c]||(f[c]=[])).push(d)},emit:function(c){var d=g.call(arguments,1),a=f[c],e,h=0;if(a)for(;e=a[h++];)e.apply(null,d)}}});
lofty("config",["lang"],function(f){var g=this.cache,c=g.config={},d=g.configRules={},g={addRule:function(a,c){d[a]={rule:c,keys:[]};return this},addRuleKey:function(a,c){d[c]&&d[c].keys.push(a);return this}};g.addRule("object",function(a,c,d){if(a){for(var f in d)a[f]=d[f];return!0}return!1}).addRule("array",function(a,c,d){a?a.push(d):this[c]=[d];return!0});this.config=function(a){for(var e in a){var g=a[e],j=c[e],m=e,l=g,k=!1,b=void 0,n=void 0;for(n in d)if(k)break;else b=d[n],k=-1<f.indexOf(b.keys,
m)&&b.rule.call(c,j,m,l);k||(c[e]=g)}};return g});lofty("alias",["config","event"],function(f,g){var c=this.cache.config;f.addRuleKey("alias","object");return function(d){var a=c.alias,e;if(a&&(e=a[d.id]))d.id=e;g.emit("alias",d)}});
lofty("module",["global","lang","event","alias"],function(f,g,c,d){var a=[],e=0,h=this.cache.modules={},j={get:function(b){b={id:b};d(b);return h[b.id]},has:function(b){return j.get(b)||l[b]?!0:!1},hasDefine:function(b){return h[b]?!0:!1},isAnon:function(b){return""===b.id},save:function(b){h[b._id||b.id]=b},autocompile:function(b){j.isAnon(b)&&j.compile(b)},compile:function(b){try{if(g.isFunction(b.factory)){var a=[],d=b.deps;g.isArray(d)&&g.forEach(d,function(c){var d;c=(d=l[c])?d(b):j.require(c,
b);a.push(c)});var e=b.factory.apply(null,a);void 0!==e?b.exports=e:b.entity&&(b.exports=b.entity.exports);b.entity&&delete b.entity}else void 0!==b.factory&&(b.exports=b.factory);c.emit("compiled",b)}catch(f){c.emit("compileFail",f,b)}},require:function(b){var a=j.get(b);a?(a.visits||(a.visits++,j.compile(a)),c.emit("required",a),b=a.exports):(c.emit("requireFail",{id:b}),b=null);return b}},m=function(b,a,c){this.id=b;this.deps=a||[];this.factory=c;this.exports={};this.visits=0;""===b&&(b="__!_lofty_anonymous_"+
e,e++,this._id=b)},l={require:function(){function b(b){return j.require(b)}c.emit("makeRequire",b);return b},exports:function(b){return b.exports},module:function(b){b.entity={id:b.id,exports:b.exports};return b.entity}},k=f.define;this.noConflict=function(){f.define=k};this.define=function(b,d,e){var f;f=arguments.length;1===f?(e=b,b=""):2===f&&(e=d,d=a,g.isString(b)||(d=b,b=""));if(j.hasDefine(b))return c.emit("existed",{id:b}),null;f=new m(b,d,e);c.emit("define",f);j.save(f);j.autocompile(f)};
f.define=this.define;return j});
lofty("console",["global","lang"],function(f,g){var c=f.document,d=[],a=null,e=!1,h=function(d){var e=c.createElement("li");e.style.color="warn"===d.type?"red":"#000";e.innerHTML=d.message;a.appendChild(e)},j=function(e){c.body?(c.body.appendChild(e),a=c.createElement("ol"),a.style.listStyleType="decimal",e.appendChild(a),g.forEach(d,function(a){h(a)})):f.setTimeout(function(){j(e)},200)};return function(f,g){var k={message:f,type:g||"log"};if(!e){var b=c.createElement("div");b.id="lofty-debug-console";
b.style.margin="10px 0";b.style.border="1px dashed red";b.style.padding="4px 8px";b.style.fontSize="14px";b.style.lineHeight="1.5";b.style.textAlign="left";j(b);e=!0}a?h(k):d.push(k)}});
lofty("debug",["global","config","console","request","require"],function(f,g,c,d,a){var e=this,h=this.log=function(){};g.addRule("debug",function(g,m,l){e.log=l?f.console?function(a,b){f.console[b||"log"](a)}:function(e,b){c?c(e,b):d&&d("lofty/kernel/console",function(){c||(c=a("console"));c(e,b)})}:h;this[m]=l;return!0}).addRuleKey("debug","debug")});
lofty("alicn",["global","event"],function(f,g){var c=/\.css(?:\?|$)/,d=/([a-z])([A-Z])/g;this.config({hasStamp:!0,resolve:function(a){a=a.replace(d,function(a,c,d){return c+"-"+d}).toLowerCase();var e=a.split("/"),f=e[0],g=c.test(a)?"css/":"js/";switch(f){case "lofty":case "avid":a="/fdevlib/"+g+a;break;case "sys":a="/sys/"+g+e.slice(1).join("/")}return a},debug:function(){var a=!1;0<f.location.href.indexOf("lofty.debug=true")&&(a=!0);return a}()});this.appframe=function(a){f[a]={log:this.log,define:this.define,
on:g.on}}});
